trigger:
  - main

pool:
  azureSubscription: 'SiteConnection'
  vmImage: ubuntu-latest

steps:
  - task: AzureContainerApps@0
    displayName: Build and deploy Container App
    inputs:
      connectedServiceNameARM: $(azureSubscription)
      appSourcePath: '$(Build.SourcesDirectory)'
      acrName: 'renzositecontainerregistry'
      containerAppName: 'site-container'
      resourceGroup: 'basic-site'