version: "3.9"
name: "site"
services:
  ui-vue:
    container_name: ui-vue
    image: vue3-ui-image
    build: services/ui-vue
    ports:
      - "8080:8080"
  ui-svelte:
    container_name: ui-svelte
    image: svelte-ui-image
    build: services/ui-svelte
    ports:
      - "8081:8080"
