apiVersion: v1
kind: Service
metadata:
  name: svelte-site-service
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  selector:
    app: svelte-site
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
